# Generated by Django 6.0.6 on 2026-07-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите полное название', max_length=100, verbose_name="Books's title")),
                ('author', models.CharField(max_length=100, verbose_name='Author(s)')),
                ('published_date', models.DateField(verbose_name='Date of publish')),
                ('count', models.IntegerField(verbose_name="Book's count")),
            ],
        ),
    ]
